apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fred-demo-cert-issuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/workshops.git
    path: 2024-austin/registry-test/clusters/fred-demo/cert-issuers
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
