apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: east-cert-issuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/navigate.git
    path: argocd/sync-waves/registry/clusters/fred-demo
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
