apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fred-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: https://github.com/kubefirst/workshops.git
    path: argocd/sync-waves/registry/clusters/fred-demo
    targetRevision: sync-waves
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
